version: "3.8"
services:
  customer:
    container_name: customers
    build: 
      context: ./services/customers
      dockerfile: Dockerfile
    ports:
      - 6061:6061
    volumes:
      - ./services/customers:/app
    depends_on:
      - lmsdb
    links:
      - lmsdb
    restart: unless-stopped

  lmsdb:
    container_name: lms_db
    build:
      context: ./services/db
      dockerfile: Dockerfile
    ports:
      - 5432:5432